api/urls.py
from django.conf.urls import patterns, url, include
from django.conf import settings

import views as apiview
import rest_framework_swagger

from rest_framework.urlpatterns import format_suffix_patterns
# from rest_framework.authtoken import views
urlpatterns = patterns('',
    # Examples:
    url(r'^jobs/$', apiview.JobsDetail.as_view()),
    url(r'^jobs/(?P<pk>\w+)/$', apiview.JobDetail.as_view()),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^api-auth/$', apiview.obtain_auth_token),
        url(r'^docs/', include('rest_framework_swagger.urls')),
        url(r'^users/(?P<pk>\w+)/$', apiview.UsersDetail.as_view()),
		url(r'^signup/$', apiview.UserSignup.as_view()),
		# url(r'^users/$', apiview.UsersList.as_view()),
        url(r'^verify/$', apiview.VerifyPhone.as_view(), name='verifyPhoneFromApp'),
        url(r'^getstatus/$', apiview.CheckPhoneStatus.as_view(),),
        ) 

urlpatterns = format_suffix_patterns(urlpatterns)

apps/jobs/urls.py
from django.conf.urls import patterns, include, url
# from django.contrib import admin
# admin.autodiscover()

from apps.jobs import views as jobviews

urlpatterns = patterns('',
    url(r'^calendar/events/$', jobviews.events, name='jobCalendarEvents'),
    url(r'^calendar/$', jobviews.calendar, name='jobCalendar'),
    url(r'^scheduler/update/(?P<job_scheduler_id>[\w\d]+)/$', jobviews.updateJobScheduler, name='updateJobScheduler'),
    url(r'^scheduler/(?P<job_scheduler_id>[\w\d]+)/$', jobviews.viewJobScheduler, name='jobScheduler'),
    url(r'(?P<job_id>\w+)/$', jobviews.viewJob, name='viewJob'),

)

jobs/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
# from django.contrib import admin
# admin.autodiscover()

from jobs import views as jobviews

urlpatterns = patterns('',
    url(r'(?P<job_id>\w+)/$', jobviews.viewJob, name='viewJob' ),
)

thm/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
# from django.contrib import admin
# admin.autodiscover()

from apps.users import views as userviews
from apps.jobs import views as jobviews
from .views import index
import logging


urlpatterns = patterns(
    '',
    url(r'^signin/$', userviews.signin, name='signin'),
    url(r'^logout/$', userviews.logout, name='logout'),
    url(r'^home/$', userviews.home, name='home'),
    # url(r'^createhandymen/$', userviews.createhandymen, name='createhandymen'),
    # url(r'^createuser/', userviews.createUser, name='createUser'),
    # url(r'^newuser/$', userviews.viewEBUser, name='viewEBUser'),
    url(r'^createjob/$', jobviews.createJob, name='createJob'),
    url(r'^registeruser/$', userviews.joinasuser, name='registeruser'),
    url(r'^e48kucfb5pq/$', userviews.smsEndpoint, name='smsEndpoint'),
    url(r'^4DEa6cvdaP0/$', userviews.gaTracker, name='gaTracker'),
    url(r'^verify/$', userviews.verifyPhone, name='verifyPhone'),
    url(r'^sendvrfcode/$', userviews.sendVrfCode, name='sendVrfCode'),
    url(r'^settings/$', userviews.userSettings, name='userSettings'),
    url(r'^settings/changepassword/$', userviews.changePassword, name='changePassword'),
    url(r'^resetpassword/', userviews.resetPasswordToken, name='resetPasswordToken'),
    url(r'^forgetpassword/$', userviews.sendPasswdVrfCode, name='sendPasswdVrfCode'),
    url(r'^search/', include('apps.search.urls')),
    url(r'^users/', include('apps.users.urls')),
    url(r'^faq/', include('apps.faq.urls')),
    url(r'^jobs/', include('apps.jobs.urls')),
    url(r'^work/', include('apps.job_gallery.urls')),
    url(r'^pricing/', include('apps.pricing.urls')),
    url(r'^commission/', include('apps.commcalc.urls')),
    url(r'^subscription/', include('apps.subscription.urls')),
    url(r'^inventory/', include('apps.inventory.urls')),
    url(r'^metrics/', include('apps.metrics.urls')),
    url(r'^$', index, name='index'),
)

if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(r'^api/v1/', include('api.urls')),
        url(r'^signup/$', userviews.signup, name='signup'),
        url(r'^profile/$', userviews.myProfile, name='myProfile'),
    )

urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

apps/jobs/models.py
import jsonfield
import uuid
from django.contrib.gis.db import models
from djmoney.models.fields import MoneyField
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from apps.subscription.models import Subscriber
from apps.users.models import UserProfile


# Create your models here.

# Job Statuses
STATUS_SELECTION = (
    ('0', 'New'),
    ('1', 'Inspection'),
    ('2', 'Accepted'),
    ('3', 'Completed'),
    ('4', 'Rejected'),
    ('5', 'Discarded'),
)

# Type of jobs
JOBS_SELECTION = (
    ('0', 'N/A'),
    ('1', 'Plumbing'),
    ('2', 'Electrical'),
    ('3', 'Furnishing'),
    ('4', 'Masonry'),
)


# Returns a hash that is used as identifier for jobs
def getUniqueUUID():
    uniqueID = ''.join(str(uuid.uuid4()).split('-'))
    return uniqueID


class Jobs(models.Model):
    """
    The jobs model
    """
    # reference id for jobs
    # not the primary key though
    jobref = models.CharField(
        _('jobref'),
        max_length=100, unique=True, default=getUniqueUUID)
    # Customer's usertype is 2 so limiting the choices
    # customer = models.ForeignKey(
    #     UserProfile,
    #     limit_choices_to={'user_type': '2'},
    #     related_name='jobs')
    customer = models.ForeignKey(
        Subscriber,
        related_name='jobs_subscriber'
        )
    fee = MoneyField(
        _('fee'),
        decimal_places=2,
        max_digits=8,
        blank=True,
        null=True,
        default_currency='NPR',
        default=0.00)
    status = models.CharField(
        _('status'),
        max_length=1,
        choices=STATUS_SELECTION,
        default='0',)
    creation_date = models.DateTimeField(
        _('creation_date'),
        default=timezone.now)
    jobtype = models.CharField(
        _('jobtype'),
        max_length=1,
        choices=JOBS_SELECTION,
        default='0',)
    handyman = models.ManyToManyField(UserProfile, related_name='orders')
    # jobs that are deleted or are to be purged would have this flag
    # set as true, no data would be permanently removed
    ishidden = models.BooleanField(_('ishidden'), default=False)
    # distance = models.DecimalField(
    #     _('distance'),
    #     decimal_places=2,
    #     max_digits=1000, default=0)
    accepted_date = models.DateTimeField(
        _('accepted_date'),
        blank=True, null=True)
    inspection_date = models.DateField(
        _('inspection_date'),
        blank=True, null=True)
    completion_date = models.DateTimeField(
        _('completion_date'),
        blank=True, null=True)
    remarks = models.TextField(_('remarks'), blank=False)
    # location / coordinates of the exact jobsite
    location = models.PointField(srid=4326, blank=True, null=True)
    # location / landmark near the jobsite
    location_landmark = models.CharField(
        _('Nearest Address'),
        max_length=100,
        blank=True
    )
    is_paid = models.BooleanField(_('Paid'), default=False)

    objects = models.GeoManager()

    def __unicode__(self):
        return str(self.jobref)

        #Overriding
    def save(self, *args, **kwargs):
        # set a unique ID for each jobs
        if self.jobref == '':
            self.jobref = ''.join(str(uuid.uuid4()).split('-'))

        # if no location is provided while creating the job
        # user the customer's default home location
        if self.location == '' or self.location is None:
            self.location = self.customer.primary_contact_person.address_coordinates

        super(Jobs, self).save(*args, **kwargs)


class JobScheduler(models.Model):
    """Model for Job Scheduling
    """
    job = models.ForeignKey(Jobs)
    inspection_start_date = models.DateTimeField(
        _('inspection_start_date'),
        blank=True, null=True
        )
    inspection_end_date = models.DateTimeField(
        _('inspection_end_date'),
        blank=True, null=True
        )
    job_start_date = models.DateTimeField(
        _('job_start_date'),
        blank=True, null=True
        )
    job_end_date = models.DateTimeField(
        _('job_end_date'),
        blank=True, null=True
        )
    active = models.BooleanField(
        _('active'),
        default=False
        )


class JobEvents(models.Model):
    """Models for JobEvents"""

    job = models.ForeignKey(Jobs)
    event = models.IntegerField(_('event'), max_length=2, default=1)
    updated_on = models.DateTimeField(
        _('updated_on'),
        default=timezone.now)
    extrainfo = jsonfield.JSONField(
        _('extrainfo'), default='{}', max_length=9999)

    def save(self, *args, **kwargs):
        super(JobEvents, self).save(*args, **kwargs)

apps/jobs/views.py
import json
import logging

#All Django Imports
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from thm.decorators import is_superuser
from .forms import JobCreationForm, JobCreationFormAdmin, JobEditFormAdmin, JobSchedulerCompleteForm, JobSchedulerInspectionForm
import apps.job_gallery.forms as jgforms
from .handler import JobManager
from apps.commcalc.handler import CommissionManager
from libs.sparrow_handler import Sparrow
from libs import out_sms as messages
# Init Logger
logger = logging.getLogger(__name__)

@login_required
@is_superuser
def createJob(request):
    user = request.user
    jm = JobManager()
    
    if request.method == "GET":
        job_form = JobCreationFormAdmin()
        return render(request, 'createjob.html', locals())
    if request.method == "POST":
        logger.debug(request.POST)
        job_form = JobCreationFormAdmin(request.POST)
        if job_form.is_valid():
            job=job_form.save()
            jm.createJobScheduler(job)
            return redirect('home')
        if job_form.errors:
            logger.debug("Form has errors, %s ", job_form.errors)
            return render(request, 'createjob.html', locals())


@login_required
def viewJob(request, job_id):
    user = request.user
    jm = JobManager()
    job = jm.getJobDetails(job_id)
    jobstatus = int(job.status)
    job_before = job.gallery.filter(img_type=0)
    job_after = job.gallery.filter(img_type=1)
    if request.method == "POST" and user.is_superuser:
        logger.debug(request.POST)
        job_form = JobEditFormAdmin(request.POST, instance=job)
        if job_form.is_valid():
            # Job escalation moves one way and cannot be backward,
            # that means if a job's status is set as accepted it cannot be
            # reverted to New, further if it's set as Complete, it cannot be set
            # as Accepted or New
            job = jm.getJobDetails(job_id)
            if int(job_form.cleaned_data['status']) < int(job.status):
                job_form = JobEditFormAdmin(instance=job)
                return render(request, 'jobdetails.html', locals())
            if request.POST.get('status') == '3' and job.accepted_date is None:
                status_error = "Accept the job before completing it"
                return render(request, 'jobdetails.html', locals())
            # save the job with the details provided
            job_form.save()
            job = jm.getJobDetails(job_id)
            # if a job is set as accepted , update the accepted time
            # only update the accepted time once
            if job.status == '1' and job.inspection_date:
                jm.activateJobScheduler(job)
            if job.status == '2' and job.accepted_date is None:
                job.accepted_date = timezone.now()
                job.save()
                vas = Sparrow()
                if len(job.handyman.all()) > 0:
                    msg = messages.JOB_ACCEPTED_MSG.format(
                        job.handyman.all()[0].name,
                        job.handyman.all()[0].phone.as_national
                    )
                    logger.warn(msg)
                    status = vas.sendMessage(msg, job.customer.primary_contact_person)
                    logger.warn("Message status \n {0}".format(status))
                # Notify the user that the job is accepted here.
                job = jm.getJobDetails(job_id)
                jm.addCompletionToJobScheduler(job)
                job_form = JobEditFormAdmin(instance=job)
                return redirect('home')
                # return render(request, 'jobdetails.html',locals())
            # if a job is set as complete , update the completion time
            # only update the completion time once
            if job.status == '3':
                cm = CommissionManager()
                if job.completion_date is None:
                    job.completion_date = timezone.now()
                    job.save()
                    # Notify the user that the job is complete here.
                    vas = Sparrow()
                    msg = messages.JOB_COMPLETE_MSG.format(job.id)
                    logger.warn(msg)
                    status = vas.sendMessage(msg, job.customer.primary_contact_person)
                    logger.warn("Message status \n {0}".format(status))
                    job = jm.getJobDetails(job_id)
                    job_form = JobEditFormAdmin(instance=job)
                    # Add commission for that job
                    cm.addCommission(job)
                else:
                    job = jm.getJobDetails(job_id)
                    job_form = JobEditFormAdmin(instance=job)
                    cm.updateCommission(job)
                return redirect('home')
                # return render(request, 'jobdetails.html',locals())
            # if a job is set as rejected or discarded, remove the comission
            if job.status == '4' or job.status == '5':
                cm = CommissionManager()
                job = jm.getJobDetails(job_id)
                job_form = JobEditFormAdmin(instance=job)
                cm.removeCommission(job)
                jm.deactivateJobScheduler(job)
                return redirect('home')
            return redirect('home')

        if job_form.errors:
            logger.debug("Form has errors, %s ", job_form.errors)

        return render(request, 'jobdetails.html', locals())

    if user.is_superuser:
        job_form = JobEditFormAdmin(instance=job)
        img_form = jgforms.JobGalleryImageForm()
        return render(request, 'jobdetails.html', locals())

    if user.user_type==1:
        return render(request, 'jobdetails_hm.html', locals())

    return render(request, 'jobdetails_user.html', locals())

@login_required
@is_superuser
def calendar(request):
    user = request.user
    return render(request, 'calendar.html', locals())

@login_required
@is_superuser
def events(request):
    user=request.user
    data_get_from=request.GET['from']
    data_get_to=request.GET['to']
    jm = JobManager()
    events = jm.get_jobs_for_calendar(data_get_from, data_get_to)
    data=dict(result=events, success=1)
    return HttpResponse(
        json.dumps(data),
        content_type="application/json")

@login_required
@is_superuser
def viewJobScheduler(request, job_scheduler_id):
    user=request.user
    jm = JobManager()
    job_scheduler = jm.getJobScheduler(job_scheduler_id)
    job = job_scheduler.job
    job_status = job.status
    if job_status == '1':
        job_scheduler_form = JobSchedulerInspectionForm(instance=job_scheduler)
    elif job_status in ['2', '3']:
        job_scheduler_form = JobSchedulerCompleteForm(instance=job_scheduler)
    return render(request, 'job_scheduler.html', locals())

@login_required
@is_superuser
def updateJobScheduler(request, job_scheduler_id):
    user = request.user
    jm = JobManager()
    job_scheduler = jm.getJobScheduler(job_scheduler_id)
    if request.method == 'POST':
        job = job_scheduler.job
        if job.status == '1':
            job_scheduler_form = JobSchedulerInspectionForm(request.POST, instance=job_scheduler)
        elif job.status in ['2', '3']    :
            job_scheduler_form = JobSchedulerCompleteForm(request.POST, instance=job_scheduler)
        if job_scheduler_form.is_valid():
            job_scheduler_form.save()
        if job_scheduler_form.errors:
            return render(request, 'job_scheduler.html', locals())
    return redirect('home')

apps/jobs/templates/createjob.html
{% extends "admin/base.html" %}
{% block localhead %}
  {{ job_form.media }}
{% endblock localhead %}
{% block content %}
	<div class='page-container container list-table'>
	<h1><a href={% url 'home' %} class='link main-back'><</a></h1>

		<h1><span class='jobId'>Create a New Job</span></h1>

	<div class="hora-job-form">
		<div class='row'>
		<div class="col-md-6">

	<form action="" method="post">{% csrf_token %}

	{{job_form.as_p}}

	</div>
		 </div>
	</div>
	<button type="submit" class="btn btn-default submit">Update</button>
	<!-- eo hora-job-form -->
	</div>
{% endblock content %}

apps/jobs/templates/jobdetails_hm.html
{% extends "admin/base.html" %}
{% load staticfiles floppyforms %}
{% block localhead %}
<link rel="stylesheet" href={% static "css/jobcarousel.css" %}>
<link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/themes/dark-hive/jquery-ui.css" id="theme">
<link rel="stylesheet" href="//blueimp.github.io/Gallery/css/blueimp-gallery.min.css">
<!-- CSS adjustments for browsers with JavaScript disabled -->
{% endblock localhead %}
{% block content %}
<div class='page-container container list-table'>
    <h1><a href={% url 'home' %} class='link main-back'><</a></h1>

    <h1>Job <span class='jobId'>#{{job.id}} {{job.customer.subscriber_name}}
 </span>
    </h1>
    <div class="hora-job-form">
        <div class='row'>
        <div class="col-md-4">
        {% if job_before or job_after %}
        <a data-toggle="modal" id ="image-modalBefore" href="#myModalJobPhotos">
            <button type="submit" class="btn btn-block btn-default">
                <span>Photos</span>
            </button>
        </a>
        {% endif %}
             <label>Jobtype:</label> <p class="form-control">{{job.get_jobtype_display}}</p>
             <label>Remarks:</label> <p class="form-control">{{job.remarks}}</p>
             <label>Status:</label> <p class="form-control">{{job.get_status_display}}</p>
             {% if job.inspection_date %}
                <label>Inspection Date:</label> <p class="form-control">{{job.inspection_date}}</p>
             {% endif %}
             {% if job.accepted_date %}
                <label>Accepted On:</label><p class="form-control">{{job.accepted_date}}</p>
             {% endif %}
             {% if job.completion_date %}
                <label>Completed On:</label><p class="form-control">{{job.completion_date}}</p>
             {% endif %}
             <label>Commission Due:</label><p class="form-group">{{job.commission_due}}</p>
         </div>

         <div class="col-md-8">
             <label>Location Map:</label>
            <div id="map" class="map"></div>
         </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block scripts %}
{% if job_before or job_after %}
<div class="modal" id="myModalJobPhotos" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
          <button class="close" type="button" data-dismiss="modal">×</button>
          <h3 class="modal-title"></h3>
      </div>
      <div class="modal-body">
        {% if job_before %}
            <div class="carousel slide" id="myCarouselBefore">
                <div class="carousel-inner">
                    {% for img in job_before  %}
                    {% if forloop.first %}
                        <div class="item active">
                    {% else %}
                        <div class="item">
                    {% endif %}
                        <div class="bannerImage">
                            <a href="#"><img src="{{img.get_img_url}}" alt=""></a>
                        </div>
                        <div class="caption row-fluid">
                            <div class="span4"><h3>Before</h3>
                            </div>
                        </div>

                    </div><!-- /Slide1 -->
                    {% endfor %}

                </div>

                <div class="control-box">
                    <a data-slide="prev" href="#myCarouselBefore" class="jcarousel-control-prev">‹</a>
                    <a data-slide="next" href="#myCarouselBefore" class="jcarousel-control-next">›</a>
                </div><!-- /.control-box -->

            </div><!-- /#myCarousel -->
        {% endif %}

        {% if job_after %}

        <div class="carousel slide" id="myCarouselAfter">
            <div class="carousel-inner">
                {% for img in job_after  %}
                {% if forloop.first %}
                    <div class="item active">
                {% else %}
                    <div class="item">
                {% endif %}
                    <div class="bannerImage">
                        <a href="#"><img src="{{img.get_img_url}}" alt=""></a>
                    </div>
                    <div class="caption row-fluid">
                        <div class="span4"><h3>After</h3>
                        </div>
                    </div>

                </div><!-- /Slide1 -->
                {% endfor %}

            </div>

            <div class="control-box">
                <a data-slide="prev" href="#myCarouselAfter" class="jcarousel-control-prev">‹</a>
                <a data-slide="next" href="#myCarouselAfter" class="jcarousel-control-next">›</a>
            </div><!-- /.control-box -->

        </div><!-- /#myCarousel -->
        {% endif %}
      </div>
      <div class="modal-footer">
          <button class="btn btn-default btn-block" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
  </div>
  </div>
  </div>
{% endif %}
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js"></script>
<!-- The Templates plugin is included to render the upload/download listings -->
<script src="//blueimp.github.io/JavaScript-Templates/js/tmpl.min.js"></script>
<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
<script src="//blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js"></script>
<!-- The Canvas to Blob plugin is included for image resizing functionality -->
<script src="//blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js"></script>
<!-- The main application script -->
<script src={% static 'js/OpenLayers.js'%}></script>
<script src="https://maps.google.com/maps/api/js?v=3.20&sensor=false"></script>
<script type="text/javascript">
    var map;
    map = new OpenLayers.Map({
        div: "map",
        allOverlays: true
    });
    // customer coordinates
    var lonLat = new OpenLayers.LonLat({{job.location.get_coords.0}}, {{job.location.get_coords.1}}).transform('EPSG:4326', 'EPSG:3857');
    // google map layer
    var gmap = new OpenLayers.Layer.Google("ROADMAP", { type: google.maps.MapTypeId.ROADMAP });
    map.addLayer(gmap);
    // marker layer
    var markers = new OpenLayers.Layer.Markers( "Markers" );
    map.addLayer(markers);
    // set marker and center map on  marker
    markers.addMarker(new OpenLayers.Marker(lonLat));
    map.setCenter(lonLat, 14);
</script>
{% endblock scripts %}

apps/jobs/templates/jobdetails_user.html
{% extends "admin/base.html" %}
{% load staticfiles floppyforms %}
{% block localhead %}
<link rel="stylesheet" href={% static "css/jobcarousel.css" %}>
<link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/themes/dark-hive/jquery-ui.css" id="theme">
<link rel="stylesheet" href="//blueimp.github.io/Gallery/css/blueimp-gallery.min.css">
<!-- CSS adjustments for browsers with JavaScript disabled -->
{% endblock localhead %}
{% block content %}
<div class='page-container container list-table'>
    <h1><a href={% url 'home' %} class='link main-back'><</a></h1>

    <h1>Job <span class='jobId'>#{{job.id}} {{job.customer.subscriber_name}} ({{job.customer.primary_contact_person.phone}})
 </span>
    </h1>
    <div class="hora-job-form">
        <div class='row'>
        <div class="col-md-4">
        {% if job_before or job_after %}
        <a data-toggle="modal" id ="image-modalBefore" href="#myModalJobPhotos">
            <button type="submit" class="btn btn-block btn-default">
                <span>Photos</span>
            </button>
        </a>
        {% endif %}
             <label>Jobtype:</label> <p class="form-control">{{job.get_jobtype_display}}</p>
             <label>Remarks:</label> <p class="form-control">{{job.remarks}}</p>
             <label>Status:</label> <p class="form-control">{{job.get_status_display}}</p>
             {% if jobstatus < 3 %}
               <label>Experts:</label><p class="form-group">{{job.handyman.all|join:"<br>"|default:"Yet to be assigned."}}</p>
             {% endif %}
             {% if job.inspection_date %}
                <label>Inspection Date:</label> <p class="form-control">{{job.inspection_date}}</p>
             {% endif %}
             {% if job.accepted_date %}
                <label>Accepted On:</label><p class="form-control">{{job.accepted_date}}</p>
             {% endif %}
             {% if job.completion_date %}
                <label>Completed On:</label><p class="form-control">{{job.completion_date}}</p>
             {% endif %}
         </div>

         <div class="col-md-8">
             <label>Location Map:</label>
            <div id="map" class="map"></div>
         </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block scripts %}
{% if job_before or job_after %}
<div class="modal" id="myModalJobPhotos" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
          <button class="close" type="button" data-dismiss="modal">×</button>
          <h3 class="modal-title"></h3>
      </div>
      <div class="modal-body">
        {% if job_before %}
            <div class="carousel slide" id="myCarouselBefore">
                <div class="carousel-inner">
                    {% for img in job_before  %}
                    {% if forloop.first %}
                        <div class="item active">
                    {% else %}
                        <div class="item">
                    {% endif %}
                        <div class="bannerImage">
                            <a href="#"><img src="{{img.get_img_url}}" alt=""></a>
                        </div>
                        <div class="caption row-fluid">
                            <div class="span4"><h3>Before</h3>
                            </div>
                        </div>

                    </div><!-- /Slide1 -->
                    {% endfor %}

                </div>

                <div class="control-box">
                    <a data-slide="prev" href="#myCarouselBefore" class="jcarousel-control-prev">‹</a>
                    <a data-slide="next" href="#myCarouselBefore" class="jcarousel-control-next">›</a>
                </div><!-- /.control-box -->

            </div><!-- /#myCarousel -->
        {% endif %}

        {% if job_after %}

        <div class="carousel slide" id="myCarouselAfter">
            <div class="carousel-inner">
                {% for img in job_after  %}
                {% if forloop.first %}
                    <div class="item active">
                {% else %}
                    <div class="item">
                {% endif %}
                    <div class="bannerImage">
                        <a href="#"><img src="{{img.get_img_url}}" alt=""></a>
                    </div>
                    <div class="caption row-fluid">
                        <div class="span4"><h3>After</h3>
                        </div>
                    </div>

                </div><!-- /Slide1 -->
                {% endfor %}

            </div>

            <div class="control-box">
                <a data-slide="prev" href="#myCarouselAfter" class="jcarousel-control-prev">‹</a>
                <a data-slide="next" href="#myCarouselAfter" class="jcarousel-control-next">›</a>
            </div><!-- /.control-box -->

        </div><!-- /#myCarousel -->
        {% endif %}
      </div>
      <div class="modal-footer">
          <button class="btn btn-default btn-block" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
  </div>
  </div>
  </div>
{% endif %}
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js"></script>
<!-- The Templates plugin is included to render the upload/download listings -->
<script src="//blueimp.github.io/JavaScript-Templates/js/tmpl.min.js"></script>
<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
<script src="//blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js"></script>
<!-- The Canvas to Blob plugin is included for image resizing functionality -->
<script src="//blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js"></script>
<!-- The main application script -->
<script src={% static 'js/OpenLayers.js'%}></script>
<script src="https://maps.google.com/maps/api/js?v=3.20&sensor=false"></script>
<script type="text/javascript">
    var map;
    map = new OpenLayers.Map({
        div: "map",
        allOverlays: true
    });
    // customer coordinates
    var lonLat = new OpenLayers.LonLat({{job.location.get_coords.0}}, {{job.location.get_coords.1}}).transform('EPSG:4326', 'EPSG:3857');
    // google map layer
    var gmap = new OpenLayers.Layer.Google("ROADMAP", { type: google.maps.MapTypeId.ROADMAP });
    map.addLayer(gmap);
    // marker layer
    var markers = new OpenLayers.Layer.Markers( "Markers" );
    map.addLayer(markers);
    // set marker and center map on  marker
    markers.addMarker(new OpenLayers.Marker(lonLat));
    map.setCenter(lonLat, 14);
</script>
{% endblock scripts %}