api/urls.py
from django.conf.urls import patterns, url, include
from django.conf import settings

import views as apiview
import rest_framework_swagger

from rest_framework.urlpatterns import format_suffix_patterns
# from rest_framework.authtoken import views
urlpatterns = patterns('',
    # Examples:
    url(r'^jobs/$', apiview.JobsDetail.as_view()),
    url(r'^jobs/(?P<pk>\w+)/$', apiview.JobDetail.as_view()),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^api-auth/$', apiview.obtain_auth_token),
        url(r'^docs/', include('rest_framework_swagger.urls')),
        url(r'^users/(?P<pk>\w+)/$', apiview.UsersDetail.as_view()),
		url(r'^signup/$', apiview.UserSignup.as_view()),
		# url(r'^users/$', apiview.UsersList.as_view()),
        url(r'^verify/$', apiview.VerifyPhone.as_view(), name='verifyPhoneFromApp'),
        url(r'^getstatus/$', apiview.CheckPhoneStatus.as_view(),),
        ) 

urlpatterns = format_suffix_patterns(urlpatterns)

apps/users/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
# from django.contrib import admin
# admin.autodiscover()

from apps.users import views as userviews

urlpatterns = patterns('',
    url(r'(?P<userref>\w+)/$', userviews.editUserDetail, name='editUserDetail' ),
)

thm/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
# from django.contrib import admin
# admin.autodiscover()

from apps.users import views as userviews
from apps.jobs import views as jobviews
from .views import index
import logging


urlpatterns = patterns(
    '',
    url(r'^signin/$', userviews.signin, name='signin'),
    url(r'^logout/$', userviews.logout, name='logout'),
    url(r'^home/$', userviews.home, name='home'),
    # url(r'^createhandymen/$', userviews.createhandymen, name='createhandymen'),
    # url(r'^createuser/', userviews.createUser, name='createUser'),
    # url(r'^newuser/$', userviews.viewEBUser, name='viewEBUser'),
    url(r'^createjob/$', jobviews.createJob, name='createJob'),
    url(r'^registeruser/$', userviews.joinasuser, name='registeruser'),
    url(r'^e48kucfb5pq/$', userviews.smsEndpoint, name='smsEndpoint'),
    url(r'^4DEa6cvdaP0/$', userviews.gaTracker, name='gaTracker'),
    url(r'^verify/$', userviews.verifyPhone, name='verifyPhone'),
    url(r'^sendvrfcode/$', userviews.sendVrfCode, name='sendVrfCode'),
    url(r'^settings/$', userviews.userSettings, name='userSettings'),
    url(r'^settings/changepassword/$', userviews.changePassword, name='changePassword'),
    url(r'^resetpassword/', userviews.resetPasswordToken, name='resetPasswordToken'),
    url(r'^forgetpassword/$', userviews.sendPasswdVrfCode, name='sendPasswdVrfCode'),
    url(r'^search/', include('apps.search.urls')),
    url(r'^users/', include('apps.users.urls')),
    url(r'^faq/', include('apps.faq.urls')),
    url(r'^jobs/', include('apps.jobs.urls')),
    url(r'^work/', include('apps.job_gallery.urls')),
    url(r'^pricing/', include('apps.pricing.urls')),
    url(r'^commission/', include('apps.commcalc.urls')),
    url(r'^subscription/', include('apps.subscription.urls')),
    url(r'^inventory/', include('apps.inventory.urls')),
    url(r'^metrics/', include('apps.metrics.urls')),
    url(r'^$', index, name='index'),
)

if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(r'^api/v1/', include('api.urls')),
        url(r'^signup/$', userviews.signup, name='signup'),
        url(r'^profile/$', userviews.myProfile, name='myProfile'),
    )

urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

users/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
# from django.contrib import admin
# admin.autodiscover()

from users import views as userviews

urlpatterns = patterns('',
    url(r'(?P<userref>\w+)/$', userviews.editUserDetail, name='editUserDetail' ),
)

apps/users/models.py
#All Django Imports
from django.conf import settings
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from django.contrib.gis.db import models
from django.core.files import File
from django.core.files.storage import default_storage as storage
from django.core.files.base import ContentFile
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.utils import six


#All external imports (libs, packages)
import hashlib
import os
import uuid
import simplejson as json
import time
import jsonfield
import logging
from phonenumber_field.modelfields import PhoneNumberField
from rest_framework.authtoken.models import Token

# Init Logger
logger = logging.getLogger(__name__)

CITY_SELECTION = (
    ('Kathmandu', 'Kathmandu'),
    ('Lalitpur', 'Lalitpur'),
    ('Bhaktapur', 'Bhaktapur'),
)

# Create your models here.


class UserManager(BaseUserManager, models.GeoManager):

    def _create_user(self, phone, password, **extra_fields):
        """
        Creates and saves a User with the given phone and password,
        user verifies the phone with a authcode.
        Access to service is limited till the user verifies his phone number
        """
        now = timezone.now()

        if not phone:
            raise ValueError('A valid mobile number must be provided')

        user = self.model(phone=phone,
                          is_active=True, last_login=now,
                          date_joined=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, phone, password=None, **extra_fields):
        address = dict(
            streetaddress='Thirbum Marg - 4, Baluwatar',
            city='Kathmandu'
        )
        u = self._create_user(phone, password, address=address, **extra_fields)
        u.is_staff = True
        u.is_active = True
        u.is_superuser = True
        u.phone_status = True
        u.user_type = 0
        u.save(using=self._db)
        return u

    def create_staffuser(self, phone, password=None, **extra_fields):
        u = self._create_user(phone, password, **extra_fields)
        u.is_staff = True
        u.is_active = True
        u.phone_status = True
        u.save(using=self._db)
        return u

    def create_user(self, phone, password=None, **extra_fields):
        return self._create_user(phone, password, **extra_fields)


def getUniqueUUID():
    uniqueID = ''.join(str(uuid.uuid4()).split('-'))
    return uniqueID


class UserProfile(AbstractBaseUser):
    """
    User Profile
    """

    def __get_pp_path(self, profile_image):
        return 'avatars/'+str(self.userref[8:24])+'/'+str(self.__generate_hash()[:8]+'.jpg')

    id = models.AutoField(_('id'), primary_key=True)
    userref = models.CharField(
        _('userref'),
        max_length=100,
        unique=True,
        default=getUniqueUUID
    )
    name = models.CharField(_('name'), max_length=30, blank=True)
    phone_status = models.BooleanField(_('phone_status'), default=False)
    phone = PhoneNumberField(_('phone'), max_length=16, unique=True)
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    profile_image = models.ImageField(
        max_length=1024,
        upload_to=__get_pp_path,
        blank=True,
        default=''
    )
    """Account Status"""
    # 1 = Active
    # 0 = Suspended
    account_status = models.IntegerField(
        _('account_status'),
        max_length=1,
        default=1
    )
    """User Types"""
    # 0 = THM Staffs
    # 1 = Handymen
    # 2 = Households/Businesses
    # 3 = Contractors
    user_type = models.IntegerField(_('user_type'), default=2)
    is_staff = models.BooleanField(_('is_staff'), default=False)
    is_superuser = models.BooleanField(_('is_superuser'), default=False)
    is_active = models.BooleanField(default=True)
    address = jsonfield.JSONField(
        _('address'),
        default=dict(streetaddress='Tripureshwore', city='Kathmandu'),
        max_length=9999,
        blank=True
    )
    address_coordinates = models.PointField(
        _('address_coordinates'),
        srid=4326,
        default='',
        blank=True,
        null=True
    )
    current_address = models.PointField(
        _('current_address'),
        srid=4326,
        default='',
        blank=True,
        null=True
    )
    extrainfo = jsonfield.JSONField(
        _('extrainfo'),
        default='{}',
        max_length=9999
    )

    USERNAME_FIELD = 'phone'
    # REQUIRED_FIELDS = ['name']

    objects = UserManager()

    def __unicode__(self):
        return str(self.name+' ('+str(self.phone)+')')

    def get_name(self):
        return self.name

    def thumbnail_exists(self):
        from django.core.files.storage import default_storage as storage
        return storage.exists(
            os.path.join(
                settings.MEDIA_ROOT,
                os.path.splitext(
                    self.profile_image.name.lower())[0]+'_normal.jpeg'))

    def __generate_hash(self):
        return hashlib.sha256(
            str(self.date_joined) + str(time.time())).hexdigest()

    def get_lat_long(self, address):
        from libs.googleapi_handler import GeoCoding
        gc = GeoCoding()
        return gc.get_lat_long(address)

    def get_profile_pic(self):
        if storage.exists(os.path.join(
                settings.MEDIA_ROOT,
                os.path.splitext(
                            self.profile_image.name.lower())[0]+'_normal.jpeg')):
            return storage.url(self.profile_image.name.split('.')[0])+'_normal.jpeg'
        return "/static/img/logo.png"

    def create_thumbnail(self, size=400, quality=None):
        if self.profile_image != '':
            try:
                from PIL import Image
                from cStringIO import StringIO
                self.profile_image.seek(0)
                orig = self.profile_image.read()
                image = Image.open(StringIO(orig))
                quality = 85
                w, h = image.size
                if w != size or h != size:
                    if w > h:
                        diff = int((w - h) / 2)
                        image = image.crop((diff, 0, w - diff, h))
                    else:
                        diff = int((h - w) / 2)
                        image = image.crop((0, diff, w, h - diff))
                    if image.mode != "RGB":
                        image = image.convert("RGB")
                    image = image.resize((size, size), Image.ANTIALIAS)
                    # thumb = six.BytesIO()
                    file_path = os.path.join(
                        settings.MEDIA_ROOT,
                        os.path.splitext(self.profile_image.name.lower())[0]+'_normal.jpeg'
                        )
                    image.save(file_path, 'JPEG', quality=quality)
                    # thumb_file = ContentFile(thumb.getvalue())
                # else:
                    # thumb_file = File(orig)
                file_path = os.path.join(
                    settings.MEDIA_ROOT,
                    os.path.splitext(self.profile_image.name.lower())[0]+'_normal.jpeg'
                    )
                image.save(file_path, 'JPEG', quality=quality)
            except Exception, e:
                # logger.warn('file not found')
                logger.warn(e)
                return  # What should we do here?  Render a "sorry, didn't work" img?

    def save(self, *args, **kwargs):
        if type(self.address) != dict:
            self.address = json.loads(self.address)
        if self.address_coordinates == '' or self.address_coordinates is None:
            myLatLng = self.get_lat_long(self.address)
            self.address_coordinates = "POINT("+str(myLatLng['lng'])+" \
                "+str(myLatLng['lat'])+")"
        # self.create_thumbnail()
        super(UserProfile, self).save(*args, **kwargs)

# Create Token for users when a user is created
@receiver(post_save, sender=UserProfile)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)


class UserEvents(models.Model):
    """Models for Users UserEvents"""

    user = models.ForeignKey(UserProfile)
    event = models.IntegerField(_('event'), max_length=2, default=1)
    updated_on = models.DateTimeField(
        _('updated_on'),
        default=timezone.now
    )
    extrainfo = jsonfield.JSONField(
        _('extrainfo'),
        default='{}',
        max_length=9999
    )

    def save(self, *args, **kwargs):
        super(UserEvents, self).save(*args, **kwargs)


class EarlyBirdUser(models.Model):
    """
    List of customers who registered in the early phase
    """

    phone = PhoneNumberField(_('phone'), max_length=16, unique=True)
    registered_on = models.DateTimeField(
        _('updated_on'),
        default=timezone.now
    )
    confirmed = models.BooleanField(_('confirmed'), default=False)

    def __unicode__(self):
        return self.phone

    def save(self, *args, **kwargs):
        if not self.registered_on:
            self.registered_on = timezone.now
        super(EarlyBirdUser, self).save(*args, **kwargs)

# class EarlyBirdHandymen(models.Model):
#     """
#     List of Handymen who registered in the early phase
#     """

#     phone = PhoneNumberField(_('phone'), max_length=16, unique=True)
#     registered_on = models.DateTimeField(_('updated_on'),
#         default=timezone.now)

#     def save(self, *args, **kwargs):
#         if not self.registered_on:
#             self.registered_on = timezone.now
#         super(EarlyBirdHandymen, self).save(*args, **kwargs)


class UserToken(models.Model):
    """
    Token Model Class for user's verification,
    password reset and other such services
    """
    user = models.ForeignKey(UserProfile)

apps/users/templates/base.html
<html>
<head>
    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-58270740-1', 'auto');
    ga('send', 'pageview');

    </script>

    <title>This is the homepage</title>    
</head>
<body>
<a href="{% url 'home' %}">Home</a>
<a href="{% url 'logout' %}">Logout</a>
Logged in as {{user.name}} ({{user.phone}})<br>

<br><br>
{% block content %}

{% endblock content %}
</body>
</html>

apps/users/templates/changepassword.html
{% extends "admin/base.html" %}
{% block content %}
	<div class='page-container container list-table'>
	<h1><a href={% url 'userSettings' %} class='link main-back'><</a></h1>

		<h1><span class='jobId'>Change Password</span></h1>

	<div class="hora-job-form">
		<div class='row'>
		<div class="col-md-6">

	<form action="" method="post">{% csrf_token %}

	{{user_form.as_p}}

	</div>
		 </div>
	</div>
	<button type="submit" class="btn btn-default submit">Change Password</button>
	<!-- eo hora-job-form -->
	</div>
{% endblock content %}

apps/users/templates/forgetpassword.html
{% load staticfiles %}
<html>
	<head>
		<title>The Homerepair App | Reset Password</title>
		<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href={% static "css/bootstrap.css" %}>
		<link rel="stylesheet" href="https://cdn.datatables.net/1.10.4/css/jquery.dataTables.css">
		<link rel="stylesheet" href="https://cdn.datatables.net/responsive/1.0.3/css/dataTables.responsive.css">
		<link rel="stylesheet" href={% static "css/hora-admin.css" %}>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
		<script src={% static "js/bootstrap.js" %}></script>
    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-58270740-1', 'auto');
    ga('send', 'pageview');

    </script>
    {% block localhead %}          
    {% endblock localhead %}    
	</head>

<body>

	<div class="wrapper">
		
	<nav class="navbar navbar-default hora-nav">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href={% url 'home' %}><img src={% static "img/logo.png" %} class='hora-nav-brand'></a>
    </div>

  </div><!-- /.container-fluid -->
</nav>
<!-- eo nav -->


{% block content %}
    <div class='page-container container list-table'>
    <h1><a href={% url 'userSettings' %} class='link main-back'><</a></h1>

    	<h1><span class='jobId'>Forgot My Password</span></h1>

    <div class="hora-job-form">
    	<div class='row'>
    	<div class="col-md-6">

    <form action="" method="post">{% csrf_token %}

    {{user_form.as_p}}

    </div>
    	 </div>
    </div>
    <button type="submit" class="btn btn-default submit">Submit</button>
{% endblock content %}



	</div>



</body>
<script>
$(document).ready(function() {
    $('#example').DataTable( {
        responsive: true,
        "bFilter": false
    } );
} );
</script>
</html>

apps/users/templates/homepage.html
{% extends "base.html" %}
{% block content %}
<h1>This is home page</h1>

Current Open Jobs
{% for job in jobs  %}
<p>
    ============<br>
    JobType : {{job.get_jobtype_display}}<br>
    Requested By :  {{job.customer.name}}( {{job.customer.phone}} )<br>
    Details = <a href="{% url 'viewJob' job_id=job.jobref %}">{{job.jobref}}</a><br>
    Status = {{job.get_status_display}}<br>
    Handyman = {{ job.handyman.all | join:", "}}<br>
    ============
</p>
{% endfor %}

{% endblock content %}

apps/users/templates/profilepage.html
{% extends "base.html" %}
{% block content %}
Name: {{userdetails.name}}<br>
Phone: {{userdetails.phone}}<br>
Address : {{userdetails.address}}<br>
Phone Status : {{userdetails.phone_status}}<br>
Member Since : {{userdetails.date_joined}}<br>
Profile Image : {{userdetails.profile_image}}<br>    
{% endblock content %}

apps/users/templates/register.html
{% extends "admin/base.html" %}
{% block content %}
    <div class='page-container container list-table'>
    <div class="hora-job-form">
    <div class='row'>
    <div class="col-md-6">
    Register a new number here !
    <form action="{% url 'registeruser' %}" method="post"> {%csrf_token%}
        <input type="text" name='phone' placeholder='+977 Mobile Number' class="form-control">
        <button type="submit" class="btn btn-default submit">Register</button>
    </form>

    </div>
         </div>
    </div>
    <!-- eo hora-job-form -->
    </div>
{% endblock content %}

apps/users/templates/resetpassword.html
{% load staticfiles %}
<html>
	<head>
		<title>The Homerepair App | Reset Password</title>
		<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href={% static "css/bootstrap.css" %}>
		<link rel="stylesheet" href="https://cdn.datatables.net/1.10.4/css/jquery.dataTables.css">
		<link rel="stylesheet" href="https://cdn.datatables.net/responsive/1.0.3/css/dataTables.responsive.css">
		<link rel="stylesheet" href={% static "css/hora-admin.css" %}>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
		<script src={% static "js/bootstrap.js" %}></script>
    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-58270740-1', 'auto');
    ga('send', 'pageview');

    </script>
    {% block localhead %}          
    {% endblock localhead %}    
	</head>

<body>

	<div class="wrapper">
		
	<nav class="navbar navbar-default hora-nav">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href={% url 'home' %}><img src={% static "img/logo.png" %} class='hora-nav-brand'></a>
    </div>

  </div><!-- /.container-fluid -->
</nav>
<!-- eo nav -->


{% block content %}
    <div class='page-container container list-table'>
    <h1><a href={% url 'userSettings' %} class='link main-back'><</a></h1>

    	<h1><span class='jobId'>Reset Password</span></h1>

    <div class="hora-job-form">
    	<div class='row'>
    	<div class="col-md-6">

    <form action="{{reset_url}}" method="post">{% csrf_token %}

    {{user_form.as_p}}

    </div>
    	 </div>
    </div>
    <button type="submit" class="btn btn-default submit">Submit</button>
{% endblock content %}



	</div>



</body>
<script>
$(document).ready(function() {
    $('#example').DataTable( {
        responsive: true,
        "bFilter": false
    } );
} );
</script>
</html>

apps/users/templates/signin.html
<html>
<head>
    <title>THM - Signin</title>
</head>
<body>
    <h1>Login Here</h1>
    <form action="{% url 'signin' %}" method="POST">{% csrf_token %}
        <input name='phone' type='text'><br>
        <input name='password' type='password'>
        <input type='submit'>
        {% if auth_form.password.errors %}
        {{ auth_form.password.errors }}
        {% endif %}
        {% if auth_form.errors %}
            {{ auth_form.non_field_errors }}
        {% endif %}
    </form>
</body>
</html>

apps/users/templates/signup.html
<html>
<head>
    <title>THM - Signup</title>
</head>
<body>
    <h1>Signup Here</h1>
    <form action="{% url 'signup' %}" method="POST">{% csrf_token %}
        <input name='phone' type='text' placeholder="+97798xxxxxxxx"><br>
        {{ user_form.phone.errors }}
        <input name='name' type='text' placeholder="Name"><br>
        {{ user_form.name.errors }}
        <input name='password1' type='password' placeholder="password"><br>
        {{ user_form.password1.errors }}
        <input name='password2' type='password' placeholder="confirm password"><br>
        {{ user_form.password2.errors }}
        <input name='city' type='text' value="Kathmandu"><br>
        {{ user_form.city.errors }}
        <input name='streetaddress' type='text' placeholder="Thirbum Marg - 4, Baluwatar"><br>
        {{ user_form.streetaddress.errors }}
        <input type='submit'>
    </form>
</body>
</html>

apps/users/templates/tokenresetpassword.html
{% load staticfiles %}
<html>
	<head>
		<title>The Homerepair App | Reset Password</title>
		<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href={% static "css/bootstrap.css" %}>
		<link rel="stylesheet" href="https://cdn.datatables.net/1.10.4/css/jquery.dataTables.css">
		<link rel="stylesheet" href="https://cdn.datatables.net/responsive/1.0.3/css/dataTables.responsive.css">
		<link rel="stylesheet" href={% static "css/hora-admin.css" %}>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
		<script src={% static "js/bootstrap.js" %}></script>
    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-58270740-1', 'auto');
    ga('send', 'pageview');

    </script>
    {% block localhead %}          
    {% endblock localhead %}    
	</head>

<body>

	<div class="wrapper">
		
	<nav class="navbar navbar-default hora-nav">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href={% url 'home' %}><img src={% static "img/logo.png" %} class='hora-nav-brand'></a>
    </div>

  </div><!-- /.container-fluid -->
</nav>
<!-- eo nav -->


{% block content %}
    <div class='page-container container list-table'>
    <h1><a href={% url 'userSettings' %} class='link main-back'><</a></h1>

    	<h1><span class='jobId'>Enter your mobile and token</span></h1>

    <div class="hora-job-form">
    	<div class='row'>
    	<div class="col-md-6">

    <form action="" method="post">{% csrf_token %}

    {{user_form.as_p}}

    </div>
    	 </div>
    </div>
    <button type="submit" class="btn btn-default submit">Submit</button>
{% endblock content %}



	</div>



</body>
<script>
$(document).ready(function() {
    $('#example').DataTable( {
        responsive: true,
        "bFilter": false
    } );
} );
</script>
</html>

apps/users/templates/usersettings.html
{% extends "admin/base.html" %}
{% load staticfiles floppyforms %}
{% block localhead %}
{{user_form.media}}
{% endblock localhead %}
{% block content %}
<div class='page-container container list-table'>
	<h1><a href={% url 'home' %} class='link main-back'><</a></h1>

  <h1><span class='jobId'>User Details</span></h1>

    <div class="hora-job-form">
    <div class='row'>
        <div class="col-md-4">
            <form action="" method="post" enctype='multipart/form-data'>{% csrf_token %}
                <div class="form-group">
                  <label>Profile Picture</label><br>
                  <img src="{{user.get_profile_pic}}"></img><br>
                  {% if user.thumbnail_exists %}
                  <input id="profile_image-clear_id" name="profile_image-clear" type="checkbox">
                  <label for="profile_image-clear_id">Remove</label>
                  {% endif %}
                  <input id="id_profile_image" name="profile_image" type="file">
                  {{user_form.profile_image.errors}}
                </div>
                <div class="form-group">
                  <label>Name</label>
                  {{user_form.name}}
                  {{user_form.name.errors}}
                </div>
                <div class="form-group">
                  <label>Phone</label>
                  {{user_form.phone}}
                  {{user_form.phone.errors}}
                </div>
                <div class="form-group">
                  <label>City</label>
                  {{user_form.city}}
                </div>
                <div class="form-group">
                  <label>Streetadddress</label>
                  {{user_form.streetaddress}}
                </div>
        </div>
        <div class="col-md-8">
                <label>Exact Location on Map</label>
               {% widget user_form.address_coordinates %}
    </div>
    </div>
</div>
<button type="submit" class="btn btn-default submit">Update</button>
{% endblock content %}